### ISSUE TITLE
Issues in sign up page.

### ISSUE THREAD

**Issue by PrasuHirapara** [abhinavtyagi88/tour-and-travel#16]
@abhinavtyagi88 There are many **validation issue in form** validation in sign in page. Storing valid and quality data is important for data integrity. 
Issue: 
-**If First and last name are number type then raise error**.
-**Birthday can't be in future** i.e. it must be in the past for validation.

![image](https://github.com/user-attachments/assets/454ef582-4284-4a41-bd81-71ca40e9f5ad)
![image](https://github.com/user-attachments/assets/07cb67a4-fe86-4c6b-a3da-c15be96bd5bc)

**Comment by PrasuHirapara** [comment]
@abhinavtyagi88 Kindly assign this task under hactoberfest.

**Comment by abhinavtyagi88** [comment]
sure

**Comment by PrasuHirapara** [comment]
@abhinavtyagi88 i have requested for merge. Kindly verify and merge it.
