### ISSUE TITLE
bug fix: Fixing submission validations

### ISSUE THREAD

**Issue by PrasuHirapara** [abhinavtyagi88/tour-and-travel#18]
@abhinavtyagi88 Form not validated.

**Comment by PrasuHirapara** [comment]
@abhinavtyagi88 i have closed MR. Can you assign me hactoberfest-accepted labe. As i am taking part in it. i will push my code directly when you assign me label.

**Comment by PrasuHirapara** [comment]
@abhinavtyagi88 kindly check MR.

**Comment by PrasuHirapara** [comment]
@abhinavtyagi88 You need to take part in hactoberfest so that more contributor can take part. Please go through it so that i can get a valid pull request.

**Comment by PrasuHirapara** [comment]
@abhinavtyagi88 kindly correct typo on the label...it should be like this 
![image](https://github.com/user-attachments/assets/f2deab10-a699-4856-b9ae-92db03ee7544)

**Comment by PrasuHirapara** [comment]
kindly merge after giving corrected title

**Comment by PrasuHirapara** [comment]
@abhinavtyagi88 kindly update type and then accept merge.

**Comment by abhinavtyagi88** [comment]
Your MR has beeen merged successfully

**Comment by PrasuHirapara** [comment]
@abhinavtyagi88 there is typo in label....it should be hactober-accepted
