### ISSUE TITLE
Container not aligned properly 

### ISSUE THREAD

**Issue by RohithNair27** [abhinavtyagi88/tour-and-travel#23]
### Description

This is not a good ui, suggesting improvement

kindly assign to me with hacktober tag

### Screenshots

![image](https://github.com/user-attachments/assets/3a33d669-9359-4b93-9803-53d62e0198e1)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/abhinavtyagi88/tour-and-travel/blob/main/CONTRIBUTING.md) of this project.

**Comment by abhinavtyagi88** [comment]
Thank you for your concern. I'm currently working on its functionality, so we've planned to manage it later.
