### ISSUE TITLE
[Bug] remove node_modules and add .gitignore

### ISSUE THREAD

**Issue by vatsal-afk** [abhinavtyagi88/tour-and-travel#24]
[urgent] use a single .gitignore file for both the frontend and backend folders 

@abhinavtyagi88 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/abhinavtyagi88/tour-and-travel/blob/main/CONTRIBUTING.md) of this project.

**Comment by abhinavtyagi88** [comment]
Thanks for recommendation
