### ISSUE TITLE
[Docs] [Feature] Simplify the Project Setup Process with a Build

### ISSUE THREAD

**Issue by vatsal-afk** [abhinavtyagi88/tour-and-travel#25]
### Category of documentation update

New addition to Project Setup guidelines.

### Describe the change you think might work

The current project setup process, which involves separate commands for the frontend and backend, could be streamlined. This documentation update will include a build script or detailed guide to simplify setting up the entire project in one go.

Proposed Improvement:
A single script or command that automates these steps:
Navigate to both the frontend and Backend directories.
Install dependencies for both.
Start both the frontend and backend servers simultaneously.
Example of a potential solution:
Create a setup.sh or setup.bat script that handles these processes:
```

#!/bin/bash
cd frontend
npm install
npm start &
cd ../Backend
npm install
npm run start
```
Alternatively, update the documentation to include instructions for setting up concurrently using tools like concurrently for Node.js. @abhinavtyagi88 

Docker might not be required at this stage.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/abhinavtyagi88/tour-and-travel/blob/main/CONTRIBUTING.md) of this project.

**Comment by vatsal-afk** [comment]
I would be happy to contribute as an assignee a PR towards this issue as it would ease the development setup.
Thanks :)

**Comment by abhinavtyagi88** [comment]
sure
