### ISSUE TITLE
[Docs] : Add Apache License

### ISSUE THREAD

**Issue by Pujan-sarkar** [abhinavtyagi88/tour-and-travel#27]
### Category of documentation update

Documentation update : License adding.

### Describe the change you think might work

There is no license in your project , so i want to add it , under hacktoberfest.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/abhinavtyagi88/tour-and-travel/blob/main/CONTRIBUTING.md) of this project.

**Comment by Pujan-sarkar** [comment]
@abhinavtyagi88 assign me this issue.

**Comment by abhinavtyagi88** [comment]
sure

**Comment by abhinavtyagi88** [comment]
Can U Add apache License instead of MIT

**Comment by Pujan-sarkar** [comment]
@abhinavtyagi88 yeah sure
