### ISSUE TITLE
Enhance LoginPage : Adding a background, improve overall experience

### ISSUE THREAD

**Issue by Abhi-Jeeet** [abhinavtyagi88/tour-and-travel#8]
The current Login Page is basic and lacks modern design features. This issue aims to enhance the user experience by making the login page visually appealing and improving its overall appearance.

This is the sample of login page which I am going to implement in your site, which make your site more visually appealing and gives the smooth experience.

![Screenshot 2024-10-11 125553](https://github.com/user-attachments/assets/27a2964e-47ab-48f6-a143-3b63423d3782)

Please assign it to me and mark it as hactoberfest.

**Comment by abhinavtyagi88** [comment]
Sounds great! Excited for improvements!
